name: Prod Deploy

inputs:
    environment:
        required: true
    secrets:
        required: false

runs:
    using: composite

    steps:
        - name: List Files
          run: ls
          shell: bash

        - name: Dynamic Secrets
          run: |
              echo ${{ inputs.environment }}
              echo ${{ inputs.secrets }}
          shell: bash
