name: Prod Deploy

inputs:
    environment:
        required: true

runs:
    using: composite

    steps:
        - name: List Files
          run: ls
          shell: bash

        - name: Dynamic Secrets
          run: echo ${{ inputs.environment }}'
          shell: bash
