name: Prod Deploy

inputs:
    environment:
        required: true

runs:
    using: composite

    steps:
        - name: List Files
          run: ls

        - name: Dynamic Secrets
          run: echo ${{ secrets[format('{0}_A', inputs.environment)] }} | sed  's/./&/g'
