name: Actions Payloads

on:
    push:
        branches: develop

jobs:
    payloads:
        runs-on: ubuntu-latest
        steps:
            - name: Payloads
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: |
                  echo "$GITHUB_CONTEXT"
