name: Dynamic Environment Test

# on: push
on:
    push:
        branches: dev

jobs:
    Deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Set Timezone
              run: sudo timedatectl set-timezone Asia/Seoul

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Other Branch
              if: github.ref != 'refs/heads/main'
              run: |
                  echo $GITHUB_REF
                  echo "other"
            - name: Main Branch
              if: github.ref == 'refs/heads/main'
              uses: ./.github/actions/prod
              with:
                  environment: "PROD"
                  secrets: ${{ secrets.PROD_B }}
