name: Actions Events

on:
    push:
        branches: main

jobs:
    evnets:
        runs-on: ubuntu-latest
        steps:
            - name: workflow_run
              env:
                  WORKFLOW_RUN: ${{github.evnet.workflow_run}}
              run: |
                  echo $WORKFLOW_RUN
