name: Actions Events

on:
    push:
        branches: main

jobs:
    evnets:
        runs-on: ubuntu-latest
        steps:
            - name: workflow_run
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: |
                  echo "$GITHUB_CONTEXT"
