name: Custom Action Test

on: push

jobs:
    Custom_Action:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Make Dot ENV
              env:
                  ENV: ${{secrets.ENV}}
              run: |
                  echo "${ENV}" > .env

            # - name: File SCP
            #   uses: appleboy/scp-action@master
            #   with:
            #       host: ${{secrets.HOST}}
            #       username: ${{secrets.USERNAME}}
            #       key: ${{secrets.PRIVATE_KEY}}
            #       source: ".env"
            #       target: "/home/ec2-user"

            - name: Docker Deployment
              uses: cloudcoke/docker-deploy@main
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  ecr-repository: ${{ secrets.ECR_REPOSITORY }}
                  docker-container-port: ${{ secrets.CONTAINER_PORT }}
                  docker-container-name: ${{ secrets.CONTAINER_NAME }}
                  use-env-file: true
                  ssh-host: ${{ secrets.HOST }}
                  ssh-username: ${{ secrets.USERNAME }}
                  ssh-private-key: ${{ secrets.PRIVATE_KEY }}
