name: Custom Action Test

on: push

jobs:
    Custom_Action:
        runs-on: ubuntu-latest
        steps:
            - uses: cloudcoke/docker-deploy@main
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  ecr-repository: ${{ secrets.ECR_REPOSITORY }}
