name: Custom Action Test

on: push

jobs:
    Custom_Action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Docker Deployment
              uses: cloudcoke/docker-deploy@main
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  ecr-repository: ${{ secrets.ECR_REPOSITORY }}
