name: Dynamic Checkout

on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: Select app
        options:
          - hello
          - world

jobs:
  dynamic_checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Set checkout paths
        id: paths
        run: |
          echo 'paths<<EOF' >> $GITHUB_OUTPUT
          echo "apps/${{ inputs.app }}" >> $GITHUB_OUTPUT
          echo "package.json" >> $GITHUB_OUTPUT
          echo "foo.txt" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Echo checkout paths
        run: |
          echo "${{ steps.paths.outputs.paths }}"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ steps.paths.outputs.paths }}

      - name: ls
        run: |
          ls