name: Dynamic Checkout

on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: Select app
        options:
          - kiweb
          - url

jobs:
  dynamic_checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Set checkout paths
        id: paths
        run: |
          echo 'paths<<EOF' >> $GITHUB_OUTPUT
          echo "apps/${{ inputs.app }}" >> $GITHUB_OUTPUT
          echo "package.json" >> $GITHUB_OUTPUT
          echo "package-lock.json" >> $GITHUB_OUTPUT
          echo "tsconfig.json" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Echo checkout paths
        run: |
          echo ${{ steps.paths.outputs.paths }}