name: Dynamic Environment Test

on: push

jobs:
    Deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Other Branch
              if: github.ref != 'refs/heads/main'
              run: |
                  echo $GITHUB_REF
                  echo "other"
            - name: Main Branch
              if: github.ref == 'refs/heads/main'
              run: |
                  echo $GITHUB_REF
                  echo "main"
