name: Dynamic Checkout

on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: Select app
        options:
          - hello
          - world

jobs:
  dynamic_checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            apps/${{ inputs.app }}
            package.json
            foo.txt

      - name: ls
        run: |
          echo "=== ls status ==="
          ls
          echo "=== ls apps status ==="
          ls apps