name: Dynamic Secrets Test

on:
    push:
        branches: main

jobs:
    Dev:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: DEV
        steps:
            - run: echo ${{ secrets[format('{0}_A', env.ENVIRONMENT)] }}
    Prod:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: PROD
        steps:
            - run: echo ${{ secrets[format('{0}_B', env.ENVIRONMENT)] }}
