name: AWS Secrets Manager Test

on:
  push:
    branches:
    - main

jobs:
  secrets-manager-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Get secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          test/actions-hello
        parse-json-secrets: true

    - name: Make Dot ENV
      run: |
        env | grep '^TEST_ACTIONS_HELLO' | sed 's/^TEST_ACTIONS_HELLO_//' > .env

    - name: Upload .env file
      uses: actions/upload-artifact@v4
      with:
        name: env-file
        include-hidden-files: true
        path: .env
        retention-days: 1
