name: Slack Test

on:
    push:
        branches: main

jobs:
    Slack:
        runs-on: ubuntu-latest
        steps:
            - name: Test Success
              run: echo "hello world"

            - name: Send Message
              if: ${{always()}}
              uses: cloudcoke/slack_actions@v1
              with:
                  slack-webhook-url: ${{secrets.SLACK_WEBHOOK_URL}}
